name: Deploy para GitHub Pages

on:
  push:
    branches:
      - main  # ou 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # ou a versão que você usa

      - name: Instalar dependências (opcional)
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      - name: Build (opcional)
        run: |
          if [ -f package.json ]; then
            npm run build || echo "Sem comando build"
          fi

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # ou ./ se os arquivos estão na raiz
